name: build-and-test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential cmake git \
            python3 python3-pip clang-format clang-tidy cppcheck pkg-config \
            libaio-dev zlib1g-dev
          python3 -m pip install --user matplotlib pandas
      - name: Configure
        run: |
          mkdir -p build && cd build && cmake ..
      - name: Build
        run: |
          cd build && make -j$(nproc)
      - name: Unit tests
        run: |
          cd build && ctest --output-on-failure
      - name: Demo run (fio)
        run: |
          cd build && cmake --build . --target run_fio_demo
