name: build-and-test

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t toyssd -f Dockerfile .
      - name: Run unit tests in Docker (project only)
        run: |
          docker run --rm -t toyssd -lc "cd build && ctest -R UnitTests --output-on-failure"

  demo:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t toyssd -f Dockerfile .
      - name: Run short CTest demo and full demo in Docker
        run: |
          docker run --rm -t toyssd -lc "\
            cd build && \
            cmake -DTOYSSD_DEMO_TEST=ON -S .. -B . && \
            ctest -R FioDemoShort --output-on-failure && \
            cmake --build . --target run_fio_demo -j1\
          "
