name: build-and-test

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t toy-ssd-sim -f Dockerfile .
      - name: Run unit tests in Docker (project only)
        run: |
          docker run --rm -t toy-ssd-sim -lc "cd build && ctest -R UnitTests --output-on-failure"

  demo:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t toy-ssd-sim -f Dockerfile .
      - name: Run fio demo in Docker
        run: |
          docker run --rm -t toy-ssd-sim -lc "cd build && FIO_ENGINE=\$(pwd)/fio_plugin/libssdsim_engine.so fio --ioengine=external:\${FIO_ENGINE} --filename=/workspace/config/default.json --name=demo --rw=randwrite --size=64M --bs=4k --iodepth=8 --numjobs=1 --time_based --runtime=5"
